### ISSUE TITLE
Runtime crash 

### ISSUE THREAD

**Issue by ToastedNickel** [MFlisar/Lumberjack#16]
I recently upgraded to Gradle 8.0.1 in my Android project, and that version of Gradle enables R8 full mode by default. Now that that is enabled, I'm getting a crash in release builds:

```
 java.lang.RuntimeException: Unable to create application com.example.MyApp: java.lang.IllegalStateException: FileNamePattern [/data/user/0/com.example/files/ApplicationLog%i.txt] does not contain a valid IntegerToken
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6776)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalStateException: FileNamePattern [/data/user/0/com.example/files/ApplicationLog%i.txt] does not contain a valid IntegerToken
	at p6.b.start(Unknown Source:147)
	at gf.e.<init>(Unknown Source:257)
	at com.example.MyApp.onCreate(Unknown Source:78)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6771)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7884) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

The crash occurs in this code in my app:

```
// We add the file logger to all build configurations
fileLoggingSetup = FileLoggingSetup.NumberedFiles(
    this,
    setup = FileLoggingSetup.Setup(
        fileName = "ApplicationLog",
        fileExtension = "txt",
        logsToKeep = 3
    ),
    sizeLimit = "2MB"
)
L.plant(FileLoggingTree(fileLoggingSetup))
```

I tracked down the error to the logback library used by Lumberjack:
https://github.com/qos-ch/logback/blob/97e517511e52e9c96357384e751d38050134dd8f/logback-core/src/main/java/ch/qos/logback/core/rolling/FixedWindowRollingPolicy.java#L95

But I can't figure out why the error is occurring. Even in the error message above, there is the `%i` integer format argument, so I'm not sure what is going on. Has anyone seen this? Any idea how to fix it? Currently I can't release the app until this is resolved, or I will have to disable diagnostic logs in the app.

**Comment by MFlisar** [comment]
Maybe updating the dependency to logback-android 3.0.0 helps as it has some changes for R8 (e.g. https://github.com/tony19/logback-android/issues/229)- you may try this

**Comment by ToastedNickel** [comment]
I followed that link and I already have the proguard rules it says to add. How do I update the dependency to logback-android 3.0.0 in your library?

**Comment by MFlisar** [comment]
Should be solved with [5.3.1](https://github.com/MFlisar/Lumberjack/releases/tag/5.3.1). I updated dependencies and added some custom proguard rules on top to fix this issue as well

**Comment by ToastedNickel** [comment]
I upgraded to 6.0.2 and I'm still getting the same exception:
```
Unable to create application: java.lang.IllegalStateException: FileNamePattern
[/data/user/0/com.company.applicationname/files/ApplicationLog%i.txt] does not contain a valid IntegerToken
```

**Comment by MFlisar** [comment]
Please try adding the proguard rule yourself to your project:

https://github.com/MFlisar/Lumberjack/blob/master/library%2Fimplementations%2Ftimber%2Fconsumer-proguard-rules.pro

I'm checking this from my mobile and I think that I forgot to use the proguard file in the timber module if I see that correctly. Adding it yourself should help as well though.

I'll check that soon in more detail.

**Comment by ToastedNickel** [comment]
> Please try adding the proguard rule yourself to your project:
> 
> https://github.com/MFlisar/Lumberjack/blob/master/library%2Fimplementations%2Ftimber%2Fconsumer-proguard-rules.pro
> 
> I'm checking this from my mobile and I think that I forgot to use the proguard file in the timber module if I see that correctly. Adding it yourself should help as well though.
> 
> I'll check that soon in more detail.

I had tried that already before messaging you, but I just tried it again to make sure, and now I'm getting a NullPointerException the first time that Timber.d() gets called.
